version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mongo-agendador
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: agendador
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"
    networks:
      - agendador-mongo
    #Informando o volume onde será salvo os dados, nunca utilizar a barra invertida "\" para informar diretórios
    volumes:
      - "D:/Javanauta/volumes/mongo_agendador:/data/db"
    #Criando checagem de saúde do banco, caso esteja ok as outras aplicações como o servidor e o mong-express subirão.
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 })" ]
      interval: 10s
      timeout: 5s
      retries: 5


  mongo-express:
    image: mongo-express
    container_name: mongo-express-agendador
    restart: on-failure
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: agendador
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH: "false"

    ports:
      - "8084:8081"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - agendador-mongo


  api:
    container_name: api-agendador-mongo
    build: .
    restart: on-failure
    ports:
      - "8081:8080"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://agendador:123@mongo:27017/db_tarefa?authSource=admin
      # Quando o ms-usuario roda na MÁQUINA HOST (fora do docker), o container acessa via host.docker.internal
      # Se você colocar o ms-usuario no mesmo docker-compose, troque para: http://usuario:8080
      USUARIO_URL: http://host.docker.internal:8080
    networks:
      - agendador-mongo

networks:
  agendador-mongo:
    driver: bridge
