services:
  mongo:
    image: mongo
    restart: on-failure
    env_file:
      - .env
    ports:
      - 27017:27017
    networks:
      - agendador-mongo
    healthcheck:
      test: [ "CMD-SHELL", "mongosh -u \"$${MONGO_INITDB_ROOT_USERNAME}\" -p \"$${MONGO_INITDB_ROOT_PASSWORD}\" --authenticationDatabase $${MONGO_AUTH_SOURCE} --eval \"db.adminCommand({ ping: 1 })\"" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express
    restart: on-failure
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_HOST}
      ME_CONFIG_BASICAUTH: 'false'
    ports:
      - 8082:8081
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - agendador-mongo

  #Iniciando a tarefa de build da aplicação para inicialização
  api:
    #Informando que o build será feito a aprtir do diretório principal
    build: .
    #Informando as portas
    ports:
      - "8081:8080"
    #Informando o comando que para que essa tarefa seja executara é preciso que a tarefa DB esteja concluida e saudavel
    depends_on:
      db:
        condition: service_healthy
    #Passando as variaveis de ambiente da aplicação que será informada no aplications.properties
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/agendador-usuario?createDatabaseIfNotExist=true
      - DATABASE_USER=agendador
      - DATABASE_PASSWORD=123
    networks:
      - agendador-mongo

networks:
  agendador-mongo:
    driver: bridge